# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

### Guess the Number Game

This is a simple text-based 'Guess the Number' game where the computer picks a random number, and the player tries to guess it. The computer gives hints (higher/lower) after each guess.
"""

import random

def guess_the_number_game():
    print("\n--- Welcome to 'Guess the Number'! ---")
    player_name = input("What's your name? ")
    print(f"Hello, {player_name}! I'm thinking of a number between 1 and 100.")
    print("Can you guess it?")

    secret_number = random.randint(1, 100)
    guesses_taken = 0

    while True:
        try:
            guess = int(input("Take a guess: "))
            guesses_taken += 1

            if guess < 1 or guess > 100:
                print("Please guess a number within the range of 1 to 100.")
            elif guess < secret_number:
                print("Your guess is too low.")
            elif guess > secret_number:
                print("Your guess is too high.")
            else:
                print(f"\nGood job, {player_name}! You guessed my number in {guesses_taken} guesses!")
                break
        except ValueError:
            print("That's not a valid number. Please enter an integer.")

# Main game loop to allow playing multiple times
while True:
    guess_the_number_game()
    play_again = input("Do you want to play again? (yes/no): ").lower()
    if play_again != 'yes':
        print("Thanks for playing! Goodbye!")
        break

"""### How to run this game

1.  **In Google Colab**: You can simply run the Python cell above. It will prompt you for input directly in the output area.
2.  **For GitHub**: Copy the code from the Python cell and paste it into a new file named `guess_the_number.py` (or any other `.py` extension) on your local machine. Then, you can run it from your terminal:
    ```bash
    python guess_the_number.py
    ```

This simple project is perfect for sharing on GitHub as your first mini-game! You can even add a `README.md` file to explain the game and how to play it.
"""